### ISSUE TITLE
Allow running the API seperatly

### ISSUE THREAD

**Issue by benjick** [kodbruket/vsf-storyblok-sync#68]

**Comment by benjick** [comment]
```
storyblok:
  image: mhart/alpine-node:12
  ports:
    - '8081:8081'
  volumes:
    - './modules/vsf-storyblok-sync/packages/vsf-storyblok-extension:/var/www/src/api/extensions/vsf-storyblok-extension'
```
